FROM ubuntu:jammy
RUN \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y pkg-config build-essential ninja-build automake autoconf libtool wget curl git gcc libssl-dev bc slib squashfs-tools android-sdk-libsparse-utils jq python3-distutils scons parallel tree python3-dev python3-pip device-tree-compiler ssh cpio fakeroot libncurses5 flex bison libncurses5-dev genext2fs rsync unzip dosfstools mtools tcl openssh-client cmake expect python-is-python3 && \
  apt-get clean
RUN useradd -m builder
USER builder
WORKDIR /home/builder
