FROM ubuntu:noble
RUN \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y pkg-config build-essential ninja-build automake autoconf libtool wget curl git gcc libssl-dev bc squashfs-tools android-sdk-libsparse-utils jq python3-setuptools scons parallel tree python3-dev python3-pip device-tree-compiler ssh cpio fakeroot libncurses6 flex bison libncurses-dev genext2fs rsync unzip dosfstools mtools tcl openssh-client cmake expect python-is-python3 ccache && \
  apt-get clean
USER ubuntu
WORKDIR /home/builder
